export type FilterStateType = {
  id: 'filter',
  freq: number,
  res: number,
  attack: number,
  decay: number,
  sustain: number,
  release: number,
}

export type EffectsStateType = {
  id: 'effects',
  chorusAmount: number,
  chorusTime: number,
  glide: number,
  arpIsOn: 1 | 0;  // 1 is on
  arpTempo: number;
}

export type LFODestination = {
  id: string;
  label: string;
  moduleId: string;
  property: string;
}

export const Actions = {
  AMP_ATTACK: 'AMP_ATTACK',
  AMP_DECAY: 'AMP_DECAY',
  AMP_SUSTAIN: 'AMP_SUSTAIN',
  AMP_RELEASE: 'AMP_RELEASE',

  FILTER_FREQUENCY: 'FILTER_FREQUENCY',
  FILTER_RES: 'FILTER_RES',
  FILTER_ATTACK: 'FILTER_ATTACK',
  FILTER_DECAY: 'FILTER_DECAY',
  FILTER_SUSTAIN: 'FILTER_SUSTAIN',
  FILTER_RELEASE: 'FILTER_RELEASE',

  CHORUS_AMOUNT: 'CHORUS_AMOUNT',
  CHORUS_TIME: 'CHORUS_TIME',
  GLIDE_CHANGED: 'GLIDE_CHANGED',
  ARP_TEMPO_CHANGED: 'ARP_TEMPO_CHANGED',
  ARP_IS_ON: 'ARP_IS_ON',


  WAVE_FILE_LIST_LOADED: 'WAVE_FILE_LIST_LOADED',
  WAVE_FILE_LOAD_STARTED: 'WAVE_FILE_LOAD_STARTED',
  WAVE_FILE_LOAD_COMPLETED: 'WAVE_FILE_LOAD_COMPLETED',
  OSC_ALGORITHM_CHANGED: 'OSC_ALGORITHM_CHANGED',
  OSC_CYCLES_CHANGED: 'OSC_CYCLES_CHANGED',
  OSC_DETUNE_CHANGED: 'OSC_DETUNE_CHANGED',
  OSC_OCTAVE_CHANGED: 'OSC_OCTAVE_CHANGED',
  OSC_AMOUNT_CHANGED: 'OSC_AMOUNT_CHANGED',
  MASTER_GAIN_CHANGED: 'MASTER_GAIN_CHANGED',

  AMP_SLIDER_CHANGED: 'AMP_SLIDER_CHANGED',
  CHORUS_SLIDER_CHANGED: 'CHORUS_SLIDER_CHANGED',

  LFO_SHAPE_CHANGED: 'LFO_SHAPE_CHANGED',
  LFO_DESTINATION_CHANGED: 'LFO_DESTINATION_CHANGED',
  LFO_AMOUNT_CHANGED: 'LFO_AMOUNT_CHANGED',
  LFO_RATE_CHANGED: 'LFO_RATE_CHANGED',
  NOTE_ON: 'NOTE_ON',
  NOTE_OFF: 'NOTE_OFF',
  KEYBOARD_NOTE_SHOW: 'KEYBOARD_NOTE_SHOW',
  KEYBOARD_NOTE_HIDE: 'KEYBOARD_NOTE_HIDE',
  LOAD_PRESET_URL_DATA: 'LOAD_PRESET_URL_DATA',
} as const;




